//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// AnimationTool.rc에서 사용되고 있습니다.
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_AnimationToolTYPE           130
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        210
#define ID_VIEW_APPLOOK_OFF_XP          211
#define ID_VIEW_APPLOOK_WIN_XP          212
#define ID_VIEW_APPLOOK_OFF_2003        213
#define ID_VIEW_APPLOOK_VS_2005         214
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define IDS_EDIT_MENU                   306
#define IDD_MYFORM                      310
#define IDD_COLTOOL                     312
#define IDD_EFFECTTOOL                  313
#define IDD_ANITOOL                     314
#define IDC_TAB1                        1000
#define IDC_LIST1                       1001
#define IDC_CHECK1                      1049
#define IDC_SPHERECOLRADIO              1064
#define IDC_BOXCOLRADIO                 1065
#define IDC_COLPOSX                     1069
#define IDC_COLPOSY                     1070
#define IDC_COLPOSZ                     1071
#define IDC_COLSIZEX                    1072
#define IDC_COLSIZEY                    1073
#define IDC_COLSIZEZ                    1074
#define IDC_COLCREATEBTN                1076
#define IDC_COLDELBTN                   1077
#define IDC_COLADJUSTBTN                1078
#define IDC_COLSAVEBTN                  1079
#define IDC_COLLOADBTN                  1080
#define IDC_EDIT3                       1081
#define IDC_RADIONEDIT                  1081
#define IDC_EVENTTiMEEDIT               1081
#define IDC_EFFECTBONELIST              1082
#define IDC_EFFECTCREATEBTN             1083
#define IDC_EPOSX                       1084
#define IDC_EPOSY                       1085
#define IDC_EPOSZ                       1086
#define IDC_ESCALEX                     1087
#define IDC_ESCALEY                     1088
#define IDC_ESCALEZ                     1089
#define IDC_EROTX                       1090
#define IDC_BUTTON1                     1091
#define IDC_XFILEDELBTN                 1091
#define IDC_EFFECTSETBTN                1092
#define IDC_DELETEBTN                   1093
#define IDC_EROTY                       1094
#define IDC_EROTZ                       1095
#define IDC_RECTRENDER                  1096
#define IDC_BUTTON2                     1097
#define IDC_ANIMATIONSTART              1097
#define IDC_MESHCREATEBTN               1097
#define IDC_STATICMESHRADIO             1098
#define IDC_DYNAMICMESHRADIO            1099
#define IDC_MESHCOMBOBOX                1100
#define IDC_XFILELISTBOX                1101
#define IDC_PLAYERRADIO                 1102
#define IDC_MONSTERRADIO                1103
#define IDC_BUTTON3                     1105
#define IDC_MESHDELBTN                  1105
#define IDC_ANILISTBOX                  1106
#define IDC_SELANINAME                  1108
#define IDC_CURANITIMEEDIT              1109
#define IDC_TIMESLIDER                  1110
#define IDC_PLAYBTN                     1111
#define IDC_STOPBTN                     1112
#define IDC_SPEEDEDIT                   1113
#define IDC_STARTTIMEEDIT               1114
#define IDC_ENDTIMEEDIT                 1115
#define IDC_STARTTIMESETBTN             1116
#define IDC_ENDTiMESETBTN               1117
#define IDC_MOTIONSETBTN                1118
#define IDC_EVENTCOMBOBOX               1119
#define IDC_EVENTCHECK                  1120
#define IDC_LOOPCHECK                   1121
#define IDC_EVENTSETBTN                 1122
#define IDC_STATECOMBOBOX               1123
#define IDC_USEANIMATIONCHECK           1124
#define IDC_NEXTMOTIONCOMBOBOX          1125
#define IDC_ADDMOTIONBTN                1126
#define IDC_NEXTMOTIONLIST              1127
#define IDC_MAGICNUMBEREDIT             1128
#define IDC_CANCELTIMEEDIT              1129
#define IDC_NEXTMOTIONSET               1131
#define IDC_NEXTMOTIONDELBTN            1132
#define IDC_ANISAVEBTN                  1133
#define IDC_ANILOADBTN                  1134
#define IDC_BONELIST                    1135
#define IDC_POSXEDIT                    1136
#define IDC_POSYEDIT                    1137
#define IDC_POSZEDIT                    1138
#define IDC_SCALEXEDIT                  1139
#define IDC_ROTXEDIT                    1140
#define IDC_SCALEYEDIT                  1141
#define IDC_ROTYEDIT                    1142
#define IDC_SCALEZEDIT                  1143
#define IDC_ROTZEDIT                    1144
#define IDC_STATICMESHINFOSETBTN        1145
#define IDC_SAVESTATICBTN               1146
#define IDC_LOADSTATICBTN               1151
#define IDC_CANCELTIMEBTN               1152
#define IDC_BUTTON4                     1153
#define IDC_ANIMATIONUSESETBTN          1153

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        311
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1154
#define _APS_NEXT_SYMED_VALUE           315
#endif
#endif
