#ifndef Constant_h__
#define Constant_h__

const _uint WINSIZEX = 1600;
const _uint WINSIZEY = 900;

const _uint MAPTOOLSIZEX = 1024;
const _uint MAPTOOLSIZEY = 768;

enum RESOURCEID {RESOURCE_STATIC, RESOURCE_STAGE, RESOURCE_STAGESTATIC, RESOURCE_LOGO, RESOURCE_LOGOSTATIC, RESOURCE_TOWN, RESOURCE_MESH, RESOURCE_MESH_TOWN, RESOURCE_MESH_ICE, RESOURCE_MESH_FIRE, RESOURCE_END};
enum LOADINGID {LOADING_LOGO, LOADING_TOWN, LOADING_DUNGEON_FIRE, LOADING_DUNGEON_ICE, LOADING_END};
enum NPCID {NPC_WEAPON, NPC_ARMOR, NPC_POTION, NPC_BOOK, NPC_QUEST, NPC_END};

enum CLASSID {CLASS_FIGHTER, CLASS_HUNTER, CLASS_SHAMAN, CLASS_WITHBLADE, CLASS_MISTIC, CLASS_END};

#endif // Constant_h__
